version: '3'
services:
  meu-app-order-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-management-microservice
    image: order-management:1.0.0
    ports:
      - "5001:5001"
    volumes:
      - ./database/database-file:/app/database/database-file
      - ./log/logs-files:/app/log/logs-files
    environment:
      - API_TITLE=Order Management
      - VERSION=1.0.0
      - SECRET_KEY=Advanced Backend Development
      - PORT=5001
      - HOST=0.0.0.0
      - TZ=America/Sao_Paulo
    networks:
      - puc-microservice

networks:
  puc-microservice:
    external: true
